apiVersion: v1
kind: Service
metadata:
  name: api-wexa
spec:
  type: LoadBalancer
  selector:
    app: api-wexa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 56000
  sessionAffinity: ClientIP
